#!/usr/bin/env python2
import keepasshttp
import sys
import re

repo_info_regex = r'(\S+)=(.*)'

operation = sys.argv[1]
if operation != "get":
    sys.exit(1)

repo_info_string = sys.stdin.read()
repo_info = dict(re.findall(repo_info_regex, repo_info_string))

if 'host' not in repo_info:
    sys.stderr.write("Host not set\n")
    sys.exit(1)

session = keepasshttp.start('git-credential-keepasshttp')
if operation == "get":
    repo_logins = session.getLogins('%s://%s/' % (repo_info['protocol'], repo_info['host']))
    if repo_logins:
        print("username=%s" % repo_logins[0]['Login'])
        print("password=%s" % repo_logins[0]['Password'].value)
    else:
        sys.stderr.write("Couldn't find credentials for host\n")
        sys.exit(1)
